--USE THIS TO SELECT ALL DATA 
--FROM USER TABLES
--IN DATABASE
--Created by ALLLV

USE --DB_NAME--
GO

CREATE VIEW VW_TEMPHELPER --ALL BASE TABLES IN DB
AS 
(
	SELECT ROW_NUMBER() OVER(ORDER BY TABLE_NAME ASC) AS ROWNUM, TABLE_NAME 
	FROM INFORMATION_SCHEMA.TABLES 
	WHERE TABLE_TYPE = 'BASE TABLE'
	AND TABLE_NAME <> 'sysdiagrams' 
)
GO

DECLARE @CURRENT_TABLE_COUNT int
DECLARE @INC int
DECLARE @SQL nvarchar(max)

SET @INC = 1

SET @CURRENT_TABLE_COUNT = 
(
	SELECT COUNT(*) 
	FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_TYPE = 'BASE TABLE'
)

WHILE @INC <= @CURRENT_TABLE_COUNT
	BEGIN
	
	SET @SQL = 'IF (' + 
	'SELECT COUNT(*) FROM [' + CAST((SELECT TABLE_NAME FROM VW_TEMPHELPER WHERE ROWNUM = @INC) AS nvarchar(max)) + ']) > 0 ' +
	'BEGIN SELECT *  FROM [' + CAST((SELECT TABLE_NAME FROM VW_TEMPHELPER WHERE ROWNUM = @INC) AS nvarchar(max)) +'] END'
	EXECUTE SP_EXECUTESQL @SQL

	SET @INC = @INC + 1
	END
GO

DROP VIEW VW_TEMPHELPER
GO
